### ISSUE TITLE
Problem with first login to QCloud local version

### ISSUE THREAD

**Issue by this-is-theway** [proteomicsunitcrg/qcloud2-pipeline#88]
Hi,
I’m having trouble logging in as the admin on my local QCloud setup. I was successful with creating the database and running the web-based app with the JAR file.

Currently I’m stuck with the first login to the QCloud platform as an administrator, following step 6 in the instruction:
"Once the server is up, open http://localhost:8089 in your browser (Firefox or Google Chrome) and log in with the email you put in the YML file under the field admin-email. Currently the 8089 cannot be changed. But if you're experencing some issue with the localhost, we can change it to your particular server address. To do that please open a new issue in this current repository."

When I try to register as a new user using the `admin-email` from the YML file, I get the following error:
`Error creating the user, check your email or contact us`

When I try to log in directly with the credentials from the database (without creating the account), I get this message:
`Unable to connect with QCloud2 servers`

Can you guide me how to proceed?

Thanks!
Jacek

Environment:
- Operating System: Ubuntu 24.04.3 LTS
- Java version: openjdk version "1.8.0_462"
- Database: MySQL 8.0.43-0ubuntu0.24.04.2 for Linux on x86_64

**Comment by rolivella** [comment]
Hi, the issue stems from the fact that QCloud expects the **first user registration** with the admin email to automatically create the administrator account, but there might be configuration or connectivity issues preventing this.

## Solutions to Try

### 1. Verify Configuration File (Most Likely Issue)
Check your `yml` file and ensure:

```yml
qcloud:
  admin-email: your.admin@email.com  # This should match exactly what you're using to register
```

**Important:** The email you use for registration **must match exactly** (including case sensitivity) with the `admin-email` field in the YML file.

### 2. Database Connection Issues
The "Unable to connect with QCloud2 servers" suggests database connectivity problems. Verify:

- MySQL service is running:
  ```bash
  sudo systemctl status mysql
  ```

- Database credentials in `yml` are correct

- The QCloud database and user exist with proper privileges

- Test database connection manually:
  ```bash
  mysql -u qcloud_user -p -h localhost -P 3306 database_name
  ```

### 3. JAR Application Issues
- Ensure the JAR is running without errors:
  ```bash
  java -jar /path/to/QCloud2-1.0.23LOCAL.jar --spring.config.location=file:///path/to/config.yml
  ```
- Check the application logs for database connection errors
- Verify port 8089 is not blocked by firewall

### 4. First-Time Setup Sequence
The correct sequence should be:
1. Start the JAR application (creates database tables via Flyway)
2. Wait for "server is up" message in logs
3. Go to `http://localhost:8089`
4. **Register** (not login) using the exact admin email from YML
5. This should create the admin account automatically

### 5. Manual Database Check
If the above doesn't work, check if the admin user was created in the database:
```sql
USE your_database_name;
SELECT * FROM users WHERE email = 'your.admin@email.com';
```

### 6. Alternative Troubleshooting Steps
- Try accessing `http://127.0.0.1:8089` instead of `localhost:8089`
- Clear browser cache/cookies
- Try a different browser
- Check if any antivirus/firewall is blocking the connection

### 7. Configuration File Template
Ensure your `yml` looks like this:
```yml
datasource:
  url: jdbc:mysql://localhost:3306/your_database_name?useSSL=false
  username: "qcloud_user"
  password: "your_password"
  driver-class-name: com.mysql.jdbc.Driver

qcloud:
  admin-email: admin@yourdomain.com

**Comment by this-is-theway** [comment]
Hi, thank you for your response.

It seems that I have followed the manual correctly, but while checking the admin user in the database (from section 5: Manual Database Check) using the command:

```
USE your_database_name;
SELECT * FROM users WHERE email = 'your.admin@email.com';
```

I get the following error:

```
ERROR 1146 (42S02): Table 'your_database_name.users' doesn't exist
```

After checking which tables are present in my database, I noticed there is a table called `user`, but it is empty:

```
SELECT * FROM user;
Empty set (0.00 sec)
```

Could this give any hint as to what might be causing the login issue?

**Comment by rolivella** [comment]
Hi,

Great catch! The empty `user` table confirms that **Flyway failed to initialize the database schema**. This is almost certainly due to MySQL 8.0 authentication incompatibility.

Quick Fix

1. Switch to native password authentication:
```sql
ALTER USER 'qcloud_user'@'%' IDENTIFIED WITH mysql_native_password BY 'your_password';
FLUSH PRIVILEGES;
```

2. Update your `external_config.yml` JDBC URL:
```yml
datasource:
  url: jdbc:mysql://localhost:3306/database_name?useSSL=false&allowPublicKeyRetrieval=true&serverTimezone=UTC
  username: "qcloud_user"
  password: "your_password"
  driver-class-name: com.mysql.jdbc.Driver
```

3. Restart the JAR application and watch for Flyway migration messages in the console

4. **Verify tables were created:**
```sql
USE your_database_name;
SHOW TABLES;
```
You should now see multiple tables created by Flyway.

5. Register at http://localhost:8089 using your admin email

MySQL 8.0 uses `caching_sha2_password` by default, which the older JDBC driver in QCloud can't handle. Switching to native password should fix it immediately.

Let me know if this resolves the issue!

**Comment by this-is-theway** [comment]
Hi,

Thank you for the detailed troubleshooting steps!

Unfortunately, I'm still experiencing the same issue. When I try to register in web interface app, I still get:
`Error creating the user, check your email or contact us`

The Java application isn't producing any logs when this error occurs in the web interface. Is there a way to enable more verbose logging or debug mode to see what's actually failing?

I'm wondering if this could be a dependency issue related to different versions of the operating system or software components.

Could you please share what operating system and MySQL version you tested the software on?

Alternatively, if you have a Docker container setup with a working QCloud2 configuration, that would be very helpful for debugging.

Thanks again for your support!

**Comment by rolivella** [comment]
Hi,

Thanks for the update. Let's get verbose logging enabled to see what's actually happening.

Update your `external_config.yml` to include:

```yml
logging:
  level:
    root: INFO
    org.springframework.web: DEBUG
    org.springframework.security: DEBUG
    org.flywaydb: DEBUG
    qcloud: DEBUG

datasource:
  url: jdbc:mysql://localhost:3306/database_name?useSSL=false&allowPublicKeyRetrieval=true&serverTimezone=UTC&logger=com.mysql.cj.log.Slf4JLogger&profileSQL=true
  username: "qcloud_user"
  password: "your_password"
  driver-class-name: com.mysql.jdbc.Driver

qcloud:
  admin-email: admin@yourdomain.com
```

Then restart with log capture:
```bash
java -jar QCloud2-1.0.23LOCAL.jar --spring.config.location=file:///path/to/external_config.yml 2>&1 | tee qcloud-debug.log
```

Try registering again and look for errors in the console or `qcloud-debug.log`.


The documented requirement is **MySQL >= 14.14** (which refers to MySQL 5.x era). Your environment is:
- Ubuntu 24.04.3 + MySQL 8.0.43 + Java 8

This is significantly newer than what the software was designed for. **MySQL 8.0 introduced breaking changes** that affect older JDBC drivers.


To isolate if this is a MySQL 8.0 issue, you could test with MySQL 5.7 using Docker:

```bash
# Run MySQL 5.7 in Docker
docker run -d --name mysql57-qcloud \
  -e MYSQL_ROOT_PASSWORD=rootpass \
  -e MYSQL_DATABASE=qcloud_db \
  -e MYSQL_USER=qcloud_user \
  -e MYSQL_PASSWORD=qcloudpass \
  -p 3307:3306 \
  mysql:5.7

# Update your external_config.yml to use port 3307
# Then test if registration works
```

Before testing registration, confirm Flyway completed:

```sql
USE your_database_name;

-- Check migrations ran
SELECT * FROM flyway_schema_history;

-- Check user table structure
DESCRIBE user;

-- Should have columns like: id, email, password, enabled, etc.
```

Unfortunately, there's **no Docker container for the QCloud web application** - only for the pipeline component (ThermoRawFileParser). You'd need to containerize it yourself if desired.

If it still fails with MySQL 5.7 or after enabling debug logging, please share:
1. The error messages from `qcloud-debug.log` when registration fails
2. Output of `SELECT * FROM flyway_schema_history;`
3. Output of `DESCRIBE user;`

This will help identify if it's a MySQL version issue, a missing dependency, or something else.

**Comment by this-is-theway** [comment]
Hi,

Thanks again for troubleshooting.

Unfortunately, switching to older software (Ubuntu 18.04 and MySQL 5.7) did not help with the problem I am struggling with.

The extended debug log file showed that **no error logs appear on the server side** after getting:
`Error creating the user, check your email or contact us`

After some digging in the browser console, I found the issue! The frontend is trying to make API calls to `https://odcf-qcloud2.dkfz.de/api/node` instead of my local server at `http://localhost:8089/api/node`.

**Browser console shows:**
```
POST https://odcf-qcloud2.dkfz.de/api/node 
net::ERR_CONNECTION_REFUSED
```

It seems that the QCloud2 JAR has the frontend built with the production API URL hardcoded instead of localhost. For the LOCAL version, it would be good if the frontend could use relative URLs like `/api/node` or read the API endpoint from `external_config.yml`.

Is there a configuration I'm missing, or would this need a new build of the JAR?

If this needs a new build of the JAR, I would be glad if you could provide an updated version.

Thank you for your support!

**Comment by rolivella** [comment]
Hi,

Yes, I can rebuild the JAR with the correct configuration for local deployment. 

To build the correct version, please confirm:
1. What port you want to use (keeping 8089 or different?)
2. Any other configuration preferences for the local setup

I'll prepare a new JAR build with the frontend properly configured for local installation and share the download link with you.

This should resolve the issue completely. I'll get back to you shortly with the updated JAR.

Thanks for your patience and thorough debugging!

**Comment by this-is-theway** [comment]
Thank you for your help.

If it is possible, I would prefer to use default HTTP port 80 to avoid specifying it in the URL.
